# Generated by Django 3.1 on 2020-08-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_main', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('image_1', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('image_3', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('image_4', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('image_5', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('image_6', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
            ],
        ),
    ]
